// AIoOS License Program - IDL (Interface Description Language)
// Generated by `anchor build` for Colosseum Agent Hackathon 2026
// Anchor 0.32+ format with discriminators and snake_case conventions

import { PROGRAM_ID } from './constants';

export const IDL = {
  address: PROGRAM_ID.toBase58(),
  metadata: {
    name: "aioos_license",
    version: "0.1.0",
    spec: "0.1.0",
    description: "AIoOS Agent License NFT Program - Colosseum Agent Hackathon 2026",
  },
  instructions: [
    {
      name: "initialize",
      discriminator: [175, 175, 109, 31, 13, 152, 155, 237],
      accounts: [
        {
          name: "config",
          writable: true,
          pda: {
            seeds: [{ kind: "const", value: [99, 111, 110, 102, 105, 103] }],
          },
        },
        { name: "authority", writable: true, signer: true },
        { name: "system_program", address: "11111111111111111111111111111111" },
      ],
      args: [],
    },
    {
      name: "log_action",
      discriminator: [123, 192, 243, 96, 38, 250, 134, 135],
      accounts: [
        {
          name: "audit_entry",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [97, 117, 100, 105, 116] },
              { kind: "account", path: "license" },
              { kind: "account", path: "license.audit_count", account: "LicenseAccount" },
            ],
          },
        },
        {
          name: "license",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [108, 105, 99, 101, 110, 115, 101] },
              { kind: "account", path: "license.agent_id", account: "LicenseAccount" },
            ],
          },
        },
        { name: "owner", signer: true, relations: ["license"] },
        { name: "actor", writable: true, signer: true },
        { name: "system_program", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "action", type: "string" },
        { name: "details", type: "string" },
      ],
    },
    {
      name: "register_license",
      discriminator: [202, 139, 17, 224, 73, 121, 232, 165],
      accounts: [
        {
          name: "license",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [108, 105, 99, 101, 110, 115, 101] },
              { kind: "arg", path: "agent_id" },
            ],
          },
        },
        {
          name: "config",
          writable: true,
          pda: {
            seeds: [{ kind: "const", value: [99, 111, 110, 102, 105, 103] }],
          },
        },
        { name: "nft_mint" },
        { name: "owner", writable: true, signer: true },
        { name: "system_program", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "agent_id", type: "string" },
        { name: "license_type", type: "string" },
        { name: "permission_level", type: "string" },
        { name: "jurisdiction", type: "string" },
      ],
    },
    {
      name: "revoke_license",
      discriminator: [97, 10, 143, 67, 35, 212, 153, 8],
      accounts: [
        {
          name: "license",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [108, 105, 99, 101, 110, 115, 101] },
              { kind: "account", path: "license.agent_id", account: "LicenseAccount" },
            ],
          },
        },
        {
          name: "config",
          pda: {
            seeds: [{ kind: "const", value: [99, 111, 110, 102, 105, 103] }],
          },
        },
        { name: "authority", signer: true },
      ],
      args: [],
    },
    {
      name: "update_ptas_state",
      discriminator: [203, 198, 46, 224, 65, 143, 163, 248],
      accounts: [
        {
          name: "license",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [108, 105, 99, 101, 110, 115, 101] },
              { kind: "account", path: "license.agent_id", account: "LicenseAccount" },
            ],
          },
        },
        { name: "owner", signer: true, relations: ["license"] },
      ],
      args: [
        {
          name: "new_state",
          type: { defined: { name: "PtasState" } },
        },
      ],
    },
  ],
  accounts: [
    {
      name: "AuditEntry",
      discriminator: [254, 88, 234, 107, 205, 16, 148, 113],
    },
    {
      name: "LicenseAccount",
      discriminator: [120, 20, 28, 217, 130, 168, 223, 118],
    },
    {
      name: "ProgramConfig",
      discriminator: [196, 210, 90, 231, 144, 149, 140, 63],
    },
  ],
  types: [
    {
      name: "AuditEntry",
      type: {
        kind: "struct" as const,
        fields: [
          { name: "license", type: "pubkey" },
          { name: "action", type: "string" },
          { name: "details", type: "string" },
          { name: "timestamp", type: "i64" },
          { name: "actor", type: "pubkey" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "LicenseAccount",
      type: {
        kind: "struct" as const,
        fields: [
          { name: "agent_id", type: "string" },
          { name: "owner", type: "pubkey" },
          { name: "nft_mint", type: "pubkey" },
          { name: "ptas_state", type: { defined: { name: "PtasState" } } },
          { name: "license_type", type: "string" },
          { name: "permission_level", type: "string" },
          { name: "jurisdiction", type: "string" },
          { name: "created_at", type: "i64" },
          { name: "revoked", type: "bool" },
          { name: "audit_count", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "ProgramConfig",
      type: {
        kind: "struct" as const,
        fields: [
          { name: "authority", type: "pubkey" },
          { name: "total_licenses", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "PtasState",
      type: {
        kind: "enum" as const,
        variants: [
          { name: "Dormant" },
          { name: "Activating" },
          { name: "Active" },
          { name: "Executing" },
          { name: "Hibernating" },
          { name: "Revoked" },
        ],
      },
    },
  ],
  events: [
    {
      name: "ActionLogged",
      discriminator: [122, 6, 229, 248, 193, 108, 15, 53],
    },
    {
      name: "LicenseRegistered",
      discriminator: [88, 235, 181, 239, 115, 132, 30, 172],
    },
    {
      name: "LicenseRevoked",
      discriminator: [185, 114, 47, 171, 61, 106, 25, 24],
    },
    {
      name: "PtasStateChanged",
      discriminator: [193, 121, 83, 179, 140, 211, 243, 58],
    },
  ],
  errors: [
    { code: 6000, name: "InvalidStateTransition", msg: "Invalid PTAS state transition" },
    { code: 6001, name: "LicenseRevoked", msg: "License has been revoked and cannot be modified" },
    { code: 6002, name: "Unauthorized", msg: "Unauthorized: only the license owner or program authority can perform this action" },
    { code: 6003, name: "AgentIdTooLong", msg: "Agent ID exceeds maximum length of 64 characters" },
    { code: 6004, name: "LicenseTypeTooLong", msg: "License type exceeds maximum length of 64 characters" },
    { code: 6005, name: "PermissionLevelTooLong", msg: "Permission level exceeds maximum length of 32 characters" },
    { code: 6006, name: "JurisdictionTooLong", msg: "Jurisdiction exceeds maximum length of 64 characters" },
    { code: 6007, name: "ActionTooLong", msg: "Action string exceeds maximum length of 64 characters" },
    { code: 6008, name: "DetailsTooLong", msg: "Details string exceeds maximum length of 256 characters" },
  ],
} as const;

export type AioosLicenseIDL = typeof IDL;
